# Generated by Django 3.1.7 on 2023-11-13 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoMaterial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=50)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gramaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grosor', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('tipoMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoMaterial.tipomaterial')),
            ],
        ),
    ]
