# Generated by Django 3.1.7 on 2024-01-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Prensa', '0001_initial'),
        ('Tinta', '0001_initial'),
        ('TipoImpresion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioPrensa',
            fields=[
                ('idPrecioPrensa', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('precioColor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('precioCantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prensa.prensa')),
                ('tinta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tinta.tinta')),
                ('tipoImpresion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoImpresion.tipoimpresion')),
            ],
        ),
    ]
