# Generated by Django 3.1.7 on 2024-03-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('idTarea', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
