# Generated by Django 3.1.7 on 2023-10-03 16:46

import apps.Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to=apps.Users.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Empleado', 'Empleado'), ('Administrador', 'Administrador')], default='Empleado', max_length=20),
        ),
    ]
