# Generated by Django 3.1.7 on 2023-11-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Suaje', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suaje',
            name='margen',
        ),
        migrations.RemoveField(
            model_name='suaje',
            name='precio',
        ),
    ]
