# Generated by Django 3.1.7 on 2024-01-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suaje', '0002_auto_20231113_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='suaje',
            name='cantidad',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='suaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
    ]
